## Задание 1

In [1]:
import numpy as np

In [3]:
z = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10 ,7]])
z

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [4]:
a = z.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

## Задание 2

In [6]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3

In [9]:
a1 = a_centered[:, 0].copy()
a1

array([-1.,  0.,  1.,  1., -1.])

In [11]:
a2 = a_centered[:, 1].copy()
a2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [12]:
a_centered_sp = a1 @ a2
a_centered_sp

8.0

In [13]:
z = a_centered.shape
z

(5, 2)

In [14]:
N = z[0]
N

5

In [16]:
x = a_centered_sp / (N - 1)
x

2.0

## Задание 4

In [17]:
y = np.cov(a.T)
y

array([[1. , 2. ],
       [2. , 4.3]])

In [21]:
x = y[0][1]
x

2.0